/*
 * WSDLRawPanel.java
 *
 * Created on February 14, 2008, 11:10 PM
 */

package gui.project;


/**
 *
 * @author  chang
 */
public class WSDLRawPanel extends javax.swing.JPanel {
    
    private String wsdlRaw;
    
    /** Creates new form WSDLRawPanel */
    public WSDLRawPanel(String wsdlRaw){
        this.wsdlRaw = wsdlRaw;
        initComponents();
        showWSDLRaw();
    }
    
    private void showWSDLRaw(){
        wsdlRawTextArea.setText(wsdlRaw);
        wsdlRawTextArea.setCaretPosition(0);
    }
    
    public void setWSDLRaw(String wsdlRaw){
        this.wsdlRaw = wsdlRaw;
        showWSDLRaw();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        wsdlRawTextArea = new javax.swing.JTextArea();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        wsdlRawTextArea.setColumns(20);
        wsdlRawTextArea.setRows(5);
        wsdlRawTextArea.setName("wsdlRawTextArea"); // NOI18N
        jScrollPane1.setViewportView(wsdlRawTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea wsdlRawTextArea;
    // End of variables declaration//GEN-END:variables
    
}
