/*
 * OptionsDialog.java
 *
 * Created on February 13, 2008, 2:59 AM
 */

package gui.options;

import javax.swing.JPanel;

/**
 *
 * @author  chang
 */
public class OptionsDialog extends javax.swing.JDialog {
    
    /** Creates new form OptionsDialog */
    public OptionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        optionsList = new javax.swing.JList();
        displayPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gui.WSFApplication.class).getContext().getResourceMap(OptionsDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jScrollPane1.border.title"))); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        optionsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Network", "Dictionaries", "General" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        optionsList.setName("optionsList"); // NOI18N
        optionsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                optionsListValueChanged(evt);
            }
        });
        optionsList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                optionsListPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(optionsList);

        displayPanel.setName("displayPanel"); // NOI18N
        displayPanel.setLayout(new java.awt.GridLayout(0, 1));

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionsListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_optionsListPropertyChange
        
        if("Network".equalsIgnoreCase(evt.getPropertyName())){
            
                showNetworkOptions();
                System.out.println("network options");
                System.out.println(evt.getNewValue());
                System.out.println(evt.getOldValue());
                System.out.println("");
            
        }else if("Dictionaries".equalsIgnoreCase(evt.getPropertyName())){
            
                showDictionariesOptions();
                System.out.println("dictionaries options");
                System.out.println(evt.getNewValue());
                System.out.println(evt.getOldValue());
                System.out.println("");
            
        }else if("General".equalsIgnoreCase(evt.getPropertyName())){
            
                showGeneralOptions();
                System.out.println("general options");
                System.out.println(evt.getNewValue());
                System.out.println(evt.getOldValue());
                System.out.println("");
            
        }
    }//GEN-LAST:event_optionsListPropertyChange

    private void optionsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_optionsListValueChanged
        // TODO add your handling code here:
        switch(optionsList.getSelectedIndex()){
            case 0:         // network options
                showNetworkOptions();
                break;

            case 1:         // dictionaries options
                showDictionariesOptions();
                break;
            
            case 2:         // general options
                showGeneralOptions();
                break;

            default:        // do nothing
        }
    }//GEN-LAST:event_optionsListValueChanged
    
    private void showNetworkOptions(){
        
        if(networkPanel == null){
            networkPanel = new NetworkPanel();
        }
        
        if(displayPanel.isAncestorOf(networkPanel))
            return;
        
        displayPanel.removeAll();
        displayPanel.add(networkPanel);
        networkPanel.revalidate();
        networkPanel.repaint();
    }
    
    private void showDictionariesOptions(){
        
        if(dictionariesPanel == null){
            dictionariesPanel = new DictionariesPanel();
        }
        
        if(displayPanel.isAncestorOf(dictionariesPanel))
            return;
        
        displayPanel.removeAll();
        displayPanel.add(dictionariesPanel);
        
        dictionariesPanel.revalidate();
        dictionariesPanel.repaint();
    }
    
    private void showGeneralOptions(){
        
        if(generalPanel == null){
            generalPanel = new GeneralPanel(this);
        }
        
        if(displayPanel.isAncestorOf(generalPanel))
            return;
        
        displayPanel.removeAll();
        displayPanel.add(generalPanel);
        
        generalPanel.revalidate();
        generalPanel.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionsDialog dialog = new OptionsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList optionsList;
    // End of variables declaration//GEN-END:variables
    
    private JPanel networkPanel;
    private JPanel dictionariesPanel;
    private JPanel generalPanel;
}
